;; -*- mode: eask; lexical-binding: t -*-

(package "let-completion"
         "0.2.0"
         "Show let-binding values in Elisp completion")

(website-url "https://github.com/gggion/let-completion.el")
(keywords "lisp" "completion")

(package-file "let-completion.el")
(files "let-completion-*.el")

(script "test" "echo \"Error: no test specified\" && exit 1")

(source 'gnu)

(depends-on "emacs" "28.1")
